all:
  hosts:
    node1:
      ansible_host: vm0
    node2:
      ansible_host: vm1
    node3:
      ansible_host: vm2
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
