apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: klusters.moingster.com
spec:
  group: moingster.com
  names:
    kind: Kluster
    listKind: KlusterList
    plural: klusters
    singular: kluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Kluster is the Schema for the klusters API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: KlusterSpec defines the desired state of Kluster
          properties:
            kubernetes:
              properties:
                networkProvider:
                  type: string
                version:
                  type: string
              required:
              - networkProvider
              - version
              type: object
            nodes:
              properties:
                count:
                  type: integer
                nodeSpec:
                  properties:
                    cores:
                      type: integer
                    memoryMb:
                      type: integer
                  required:
                  - cores
                  - memoryMb
                  type: object
              required:
              - count
              - nodeSpec
              type: object
          required:
          - kubernetes
          - nodes
          type: object
        status:
          description: KlusterStatus defines the observed state of Kluster
          properties:
            reason:
              type: string
            state:
              type: string
          required:
          - reason
          - state
          type: object
      required:
      - spec
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
