apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk2
spec:
  storageClassName: csi-hostpath-sc
  dataSource:
    name: ubuntu
    kind: PersistentVolumeClaim
    apiGroup: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
