apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: disk2
spec:
  source:
    pvc:
      namespace: default
      name: ubuntu
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 6Gi
