apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.upload.target: ""
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: csi-hostpath-sc
